### ISSUE TITLE
The pet homestay option should only be visible when the website is logged in by user 

### ISSUE THREAD

**Issue by Bipulgrg** [Baroon-Shrestha/pawSome_Nepal#31]
![Screenshot 2024-05-20 124833](https://github.com/Baroon-Shrestha/pawSome_Nepal/assets/119418833/ee9fac71-0f24-446a-bb2c-533b4962d135)

**Comment by Baroon-Shrestha** [comment]
fixed the issue where the pet homestay should be shown only when the logged in user is customers.
